### ISSUE TITLE
the demo in the README doesn't work anymore

### ISSUE THREAD

**Issue by bbigras** [Mic92/cntr#11]
It shows:
![image](https://user-images.githubusercontent.com/24027/53665716-39fa8580-3c3a-11e9-9427-4bd5ec808123.png)

**Comment by Mic92** [comment]
Oh, man. No idea how to get it back.

**Comment by Mic92** [comment]
@sickill I created an account, but don't know how restore that file or link it to my account. This is my user: https://asciinema.org/~Mic-92

**Comment by Mic92** [comment]
This is the link: https://asciinema.org/a/PQB5RnRGLIPn88a1R2MtPccdy

**Comment by sickill** [comment]
@Mic92 no prob, I'll fix it.

**Comment by Mic92** [comment]
@sickill thanks a lot!

**Comment by sickill** [comment]
@Mic92 I've unarchived it, and assigned it to your "Mic-92" account.

**Comment by Mic92** [comment]
thanks
