### ISSUE TITLE
/var/lib/cntr needs to be created on the slim container before cntrfs sessions start

### ISSUE THREAD

**Issue by ramSeraph** [Mic92/cntr#14]
Otherwise mount move from ctnr-temp to ctnrfs/var/lib/cntr fails with ENOENT

Ran into this error, I could resolve it by patching cntr to create /var/lib/cntr in the parent attach process right after mountns receive.

Sorry for the sketchy details.. let me know if you need more info

**Comment by ramSeraph** [comment]
More details:
```
> uname -a
Linux ##### 4.15.0-1036-azure #38~16.04.1-Ubuntu SMP Fri Dec 7 03:21:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
> docker --version
Docker version 18.09.6, build 481bc77
```

```
dpkg-query -l | grep containerd
ii  containerd.io                          1.2.5-1                                    amd64        An open and reliable container runtime
```

**Comment by Mic92** [comment]
Should be fixed in https://github.com/Mic92/cntr/pull/15
