### ISSUE TITLE
Problems installing cntr on ark linux (manjaro KDE Plasma 18.1.5)

### ISSUE THREAD

**Issue by rene-gust** [Mic92/cntr#17]
- I use an ark linux manjaro kde plasma 18.1.5
- I installed cargo 1.41.0
- i tried to install cntr but got rust specific error messages
- anyone knows what goes wrong ?

[rene@thinky api-platform]$ cargo install cntr
    Updating crates.io index
  Installing cntr v1.1.2
   Compiling libc v0.2.66
   Compiling maybe-uninit v2.0.0
   Compiling cfg-if v0.1.10
   Compiling log v0.4.8
   Compiling bitflags v1.2.1
   Compiling pkg-config v0.3.17
   Compiling stable_deref_trait v1.1.1
   Compiling spin v0.4.10
   Compiling void v1.0.2
   Compiling thread-scoped v1.0.2
   Compiling remove_dir_all v0.5.2
   Compiling argparse v0.2.2
   Compiling owning_ref v0.3.3
   Compiling concurrent-hashmap v0.2.2
   Compiling log v0.3.9
   Compiling smallvec v0.6.13
   Compiling cntr-fuse v0.3.6
   Compiling rand v0.4.6
   Compiling time v0.1.42
   Compiling num_cpus v1.12.0
   Compiling cntr-nix v0.10.0-pre1
   Compiling parking_lot_core v0.2.14
   Compiling tempdir v0.3.7
error[E0308]: mismatched types
   --> /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    | 
   ::: /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    | 
   ::: /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    | 
   ::: /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    | 
   ::: /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    | 
   ::: /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    | 
   ::: /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    | 
   ::: /home/rene/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 7 previous errors

For more information about this error, try `rustc --explain E0308`.
   Compiling parking_lot v0.5.5
error: could not compile `cntr-nix`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cntr v1.1.2`, intermediate artifacts can be found at `/tmp/cargo-install5r9ZE3`

Caused by:
  build failed

**Comment by Mic92** [comment]
Did you by chance run `cargo update` before running `cargo build`?

**Comment by stephenmuss** [comment]
It's also the same in Ubuntu 18.04.3 using `cargo install`.

```
$ cargo install cntr
    Updating crates.io index
  Downloaded cntr v1.1.2
  Downloaded 1 crate (40.3 KB) in 4.88s
  Installing cntr v1.1.2
  Downloaded time v0.1.42
  Downloaded tempdir v0.3.7
  Downloaded concurrent-hashmap v0.2.2
  Downloaded log v0.3.9
  Downloaded argparse v0.2.2
  Downloaded parking_lot v0.5.5
  Downloaded thread-scoped v1.0.2
  Downloaded cntr-fuse v0.3.6
  Downloaded cntr-nix v0.10.0-pre1
  Downloaded spin v0.4.10
  Downloaded rand v0.4.6
  Downloaded remove_dir_all v0.5.2
  Downloaded parking_lot_core v0.2.14
  Downloaded owning_ref v0.3.3
  Downloaded smallvec v0.6.13
  Downloaded stable_deref_trait v1.1.1
  Downloaded maybe-uninit v2.0.0
   Compiling libc v0.2.66
   Compiling maybe-uninit v2.0.0
   Compiling log v0.4.8
   Compiling cfg-if v0.1.10
   Compiling bitflags v1.2.1
   Compiling pkg-config v0.3.17
   Compiling stable_deref_trait v1.1.1
   Compiling remove_dir_all v0.5.2
   Compiling void v1.0.2
   Compiling thread-scoped v1.0.2
   Compiling spin v0.4.10
   Compiling argparse v0.2.2
   Compiling cntr-fuse v0.3.6
   Compiling owning_ref v0.3.3
   Compiling concurrent-hashmap v0.2.2
   Compiling rand v0.4.6
   Compiling time v0.1.42
   Compiling num_cpus v1.12.0
   Compiling smallvec v0.6.13
   Compiling log v0.3.9
   Compiling cntr-nix v0.10.0-pre1
error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    |
   ::: /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    |
   ::: /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    |
   ::: /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    |
   ::: /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    |
   ::: /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    |
   ::: /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/macros.rs:197:26
    |
197 |                   $entry = libc::$entry,
    |                            ^^^^ expected `i32`, found `u32`
    |
   ::: /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cntr-nix-0.10.0-pre1/src/sys/resource.rs:6:1
    |
6   | / libc_enum!{
7   | |     #[repr(i32)]
8   | |     pub enum Resource {
9   | |         RLIMIT_AS,
...   |
35  | |     }
36  | | }
    | |_- in this macro invocation
    |
help: you can convert an `u32` to `i32` and panic if the converted value wouldn't fit
    |
197 |                 $entry = libc.try_into().unwrap()::$entry,
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 7 previous errors

For more information about this error, try `rustc --explain E0308`.
error: failed to compile `cntr v1.1.2`, intermediate artifacts can be found at `/tmp/cargo-installTJ0RTN`

Caused by:
  could not compile `cntr-nix`.

To learn more, run the command again with --verbose.
```

**Comment by Mic92** [comment]
Yes. cntr does not support libc 1.1.2 yet. There are some fixes needed to support this.
