### ISSUE TITLE
Attach fails: failed to setup /.cntr

### ISSUE THREAD

**Issue by st3iny** [Mic92/cntr#295]
I tested cntr the other day and it failed to attach to a container. I tried running the command as a non-root user in the docker group. It was installed via `cargo install cntr`.

Do you have any idea what is wrong here and how to fix it?

```
$ cntr attach 0531f16fe281
failed to setup /.cntr, failed to create setcap executable, Failed set file capability CAP_SYS_CHROOT on /tmp/cntr.p60d0d/cntr-exec, setxattr failed, EPERM: Operation not permitted

$ TMPDIR=/home/[redacted]/.cache cntr attach 0531f16fe281
failed to setup /.cntr, failed to create setcap executable, Failed set file capability CAP_SYS_CHROOT on /home/[redacted]/.cache/cntr.pw6ZLa/cntr-exec, setxattr failed, EPERM: Operation not permitted
```

**Comment by nc7s** [comment]
@Mic92 tagging for visibility. My daily drivers include Fedora 40 and Debian sid, on both of which cntr fails with the same error. I packaged cntr in Debian, but with this, its usefulness is seriously limited.

**Comment by Mic92** [comment]
You cannot run cntr as non-root. This has never worked. You would need to prepend sudo. The docker group is not sufficient.

**Comment by nc7s** [comment]
If so, please communicate that clearly in the docs and error messages. There's not a single occurrence of `sudo` in the README, and command examples use `$`, which conventionally represents non-root user. As podman runs rootlessly by default, one would naturally think cntr, which states it "supports podman", would also work in that setting. I can help with some docs.
