### ISSUE TITLE
Attach and Exec don't support the Posix -- command line argument convention

### ISSUE THREAD

**Issue by gfrascadorio** [Mic92/cntr#65]
The -- convention cannot be used to differentiate arguments for cntr vs arguments for the command
For example,
     cntr attach -t command cntr-/nix/store/xyzzy bash --rcfile foo.sh
fails. The issue is that cntr considers --rcfile to be a unknown option rather than an argument for bash.
If the -- convention were supported, then this probably would have worked:
    cntr attach -t command cntr-/nix/store/xyzzy -- bash --rcfile foo.sh

See a description of -- here: https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

**Comment by Mic92** [comment]
We recently switched to clippy as argument parser. Does this behavior also happen on master or what version did you use for testing?

**Comment by gfrascadorio** [comment]
Ok.  Stupid me. It does support it.  My problem was something else.
